# Generated by Django 3.2.6 on 2021-08-16 06:57

from django.db import migrations, models
import songs.audio_tools


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_alter_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='songs', validators=[songs.audio_tools.validate_is_audio]),
        ),
    ]
