# Generated by Django 3.2.6 on 2021-08-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_alter_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='img'),
        ),
    ]
