# Generated by Django 3.2.6 on 2021-08-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image_url',
            field=models.CharField(blank=True, default='media/img/default.jpg', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(default='img/default.jpg', upload_to='img'),
        ),
    ]
